{
	"entries": [
		{
				"message": "Running connect.script",
				"identifier": "START",
				"timestamp": "2023-04-18 13:38:49.652 +0900"
			},
		{
				"message": "(Duration:\"0.444\", Errors:\"1\", Exceptions:\"0\", StartTime:\"2023-04-18 13:38:49 +0900\", Successes:\"0\", TestCase:\"connect.script\", Warnings:\"0\")",
				"identifier": "EndTestCase",
				"timestamp": "2023-04-18 13:38:50.099 +0900"
			},
		{
				"message": "STMaxCallDepthExceeded: Handlers were called to a depth exceeding the maximum limit (40). HINT: One common cause for this error is a script that has been given the same name as a built-in command or function unintentionally calling itself. -- Execution Time 0:00:00 connect.script",
				"identifier": "FAILURE",
				"timestamp": "2023-04-18 13:38:50.117 +0900"
			}
	],
	"createdTimestamp": "2023-04-18 13:38:49.654 +0900"
}