<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
 <testsuite name="connect_script" package="EPF_test.suite" timestamp="2023-04-18 13:32:32.373 +0900"
 tests="1"  failures="1" errors="0" time="0.699000">
  <properties>
   <property name="RunDate" value="2023-04-18 13:32:32.373 +0900"/>
   <property name="Status" value="Failure"/>
  </properties>
  <testcase name="connect.script" assertions="1" status="failure"  time="0.693">
    <failure type="FAILURE" message="STMaxCallDepthExceeded: Handlers were called to a depth exceeding the maximum limit (40). HINT: One common cause for this error is a script that has been given the same name as a built-in command or function unintentionally calling itself. -- Execution Time 0:00:00 connect.script" />
  </testcase>
 </testsuite>
</testsuites>
